### ISSUE TITLE
Unexpected "already configured - ignoring addition request"

### ISSUE THREAD

**Issue by hilmiller** [hpcsi/losf#73]
I feel like there is a parsing error somewhere regarding aliased package names. I have a package I'm sure isn't installed or configured to be installed, failing to be added to an alias because losf says it is already added.

No relevant packages installed on node.
```
c252-101.cluster(9)# rpm -qa | grep zappa | wc -l
0
```

My desired rpm isn't in packages.config (it's in there commented out for debug purposes)
```
c252-101.cluster(13)# grep zappa-client-201503.2.0-10.el6.x86_64 /admin/losf/config/custom-packages/cluster/packages.config | grep -v '^#' | wc -l
0
```

Here is an alias with the package's dependencies, currently added to c252-101's node type. Having these installed or not does not seem to matter for this issue.
```
c252-101.cluster(27)# grep '^zappa-201503_2_0_10=' /admin/losf/config/custom-packages/cluster/packages.config
zappa-201503_2_0_10=zappa-client-fio-201503.2.0-10.el6.x86_64 name=zappa-client-fio version=201503.2.0 release=10.el6 arch=x86_64 6b53ddc00eb15d76654469a8a4267219 NODEPS IGNORESIZE
zappa-201503_2_0_10=zappa-client-drivers-2.6.32-431.23.3.201503.2.0_10.el6.x86_64 name=zappa-client-drivers version=2.6.32 release=431.23.3.201503.2.0_10.el6 arch=x86_64 dc927a3bf8adc6a37fcfb6ab8d99b7b1 NODEPS IGNORESIZE
zappa-201503_2_0_10=zappa-client-firmware-201503.2.0-10.el6.x86_64 name=zappa-client-firmware version=201503.2.0 release=10.el6 arch=x86_64 dbaab4e4f3062b62668f103483d292c9 NODEPS IGNORESIZE
zappa-201503_2_0_10=zappa-client-docs-201503.2.0-10+713531f.R name=zappa-client-docs version=201503.2.0_10+713531f.D release=1.el7.centos arch=noarch 886f494baa7e7f89f75ca6388e5c097e NODEPS IGNORESIZE
```

The problem, is when I attempt to add this RPM to that alias
```
c252-101.cluster(28)# losf addrpm --alias=zappa-201503_2_0_10 zappa-client-201503.2.0-10.el6.x86_64.rpm

** Checking on possible addition of custom RPM package: zappa-client-201503.2.0-10.el6.x86_64.rpm
   --> md5sum = ab9bfa9e9fd27646e62d9123af3f791c
   --> Cluster = cluster, Node Type = compute

   --> Would you like to add zappa-client-201503.2.0-10.el6.x86_64.rpm 
       to the alias "zappa-201503_2_0_10" for cluster?


[LosF] Enter yes/no to confirm (or -1 to add to multiple node types): yes

   --> Reading Custom package config file:
       --> /admin/losf/config/custom-packages/cluster/packages.config
       --> reading rpms for zappa-201503_2_0_10 alias....
   --> Attempting to add zappa-client-201503.2.0-10.el6.x86_64
       --> zappa-client already configured - ignoring addition request
```

And a funny thing is, I CAN add it without the alias.
```
c252-101.cluster(29)# losf addrpm zappa-client-201503.2.0-10.el6.x86_64.rpm                                                                                                                                            

** Checking on possible addition of custom RPM package: zappa-client-201503.2.0-10.el6.x86_64.rpm
   --> md5sum = ab9bfa9e9fd27646e62d9123af3f791c
   --> Cluster = cluster, Node Type = compute

   --> Would you like to add zappa-client-201503.2.0-10.el6.x86_64.rpm 
       to your local LosF config for cluster:compute nodes?


[LosF] Enter yes/no to confirm (or -1 to add to multiple node types): yes

   --> Reading Custom package config file:
       --> /admin/losf/config/custom-packages/cluster/packages.config
   --> Attempting to add zappa-client-201503.2.0-10.el6.x86_64
       --> zappa-client not previously configured - registering for addition/upgrade
   --> Updating Custom RPM config file...


Custom RPM config update complete; you can now run "update" to make changes take effect
```

Another funny thing, is that I can manually edit packages.config to include my troubled package in the alias and everything works fine and update works as expected for these packages.
```
zappa-201503_2_0_10=zappa-client-201503.2.0-10.el6.x86_64 name=zappa-client version=201503.2.0 release=10.el6 arch=x86_64 ab9bfa9e9fd27646e62d9123af3f791c NODEPS IGNORESIZE
zappa-201503_2_0_10=zappa-client-fio-201503.2.0-10.el6.x86_64 name=zappa-client-fio version=201503.2.0 release=10.el6 arch=x86_64 6b53ddc00eb15d76654469a8a4267219 NODEPS IGNORESIZE
zappa-201503_2_0_10=zappa-client-drivers-2.6.32-431.23.3.201503.2.0_10.el6.x86_64 name=zappa-client-drivers version=2.6.32 release=431.23.3.201503.2.0_10.el6 arch=x86_64 dc927a3bf8adc6a37fcfb6ab8d99b7b1 NODEPS IGNORESIZE
zappa-201503_2_0_10=zappa-client-firmware-201503.2.0-10.el6.x86_64 name=zappa-client-firmware version=201503.2.0 release=10.el6 arch=x86_64 dbaab4e4f3062b62668f103483d292c9 NODEPS IGNORESIZE
zappa-201503_2_0_10=zappa-client-docs-201503.2.0-10+713531f.R name=zappa-client-docs version=201503.2.0_10+713531f.D release=1.el7.centos arch=noarch 886f494baa7e7f89f75ca6388e5c097e NODEPS IGNORESIZE
```

**Comment by koomie** [comment]
Can I ask what version of losf is this locally? (e.g. can run "losf -v")

**Comment by hilmiller** [comment]
Sure, sorry if this was already fixed in a release.
```LosF: Version 0.47.3 ```

**Comment by koomie** [comment]
I went back to 0.47.3 but unfortunately, haven't been able to reproduce just yet. Assuming you still have these rpms, would you mind maybe trying this again in a sandbox/standalone config?  That might help and then I could have a look at your smaller config. What I was thinking was reproducing in isolation via something like the following to add each of those packages individually (i may not have the package right, so adjust to match).

````
$ export LOSF_CONFIG_DIR=/tmp/debug1
$ initconfig test
$ losf addrpm --alias=zappa-201503_2_0_10 zappa-client-fio-201503.2.0-10.el6.x86_64.rpm
$ losf addrpm --alias=zappa-client-drivers-2.6.32-431.23.3.201503.2.0_10.el6.x86_64.rpm
$ losf addrpm --alias=zappa-client-firmware-201503.2.0-10.el6.x86_64.rpm
$ losf addrpm --alias=zappa-client-docs-201503.2.0-10+713531f.R.rpm
````

Then, let's see what's in the alias:

````
$ losf showalias zappa-201503_2_0_10
````

And then let's see the error when adding the last package:

````
$ losf addrpm --alias=zappa-201503_2_0_10 zappa-client-201503.2.0-10.el6.x86_64.rpm
````

If you can drop a tarball with the resulting LOSF_CONFIG_DIR somewhere in my directory on stampede, I can take a look further.

Thanks.

**Comment by hilmiller** [comment]
Thanks! I'll try to do this sometime next week in isolation. The RPMs are under NDA unfortunately so it complicates things. Will report back!

**Comment by hilmiller** [comment]
This RPM was an anomaly, the vendor changed the way it packaged this RPM in future releases and does not have this error anymore. Closing.
